title: We Love Users
description: Accompagnement terrain pour décisions produit stratégiques.
url: "https://www.weloveusers.com"
baseurl: ""
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "googledbd4faf8e651aaa9.html"
    values:
      sitemap: false
      
exclude: [
        "package.json",
        "TODO",
        "run.sh",
        "Gemfile",
        "Gemfile.lock",
        ".ruby-version"
        ]

markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap